services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ../../volume/infra/nginx/logs:/var/log/nginx
    networks: [homelab-net]
    expose:
      - "80"
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/nginx-health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
